#!/usr/bin/env python
"""Regenerate references/codebase-map.md from the actual source.

The map exists so a task can find the right symbol without grepping 24 modules.
Because it is generated, it is cheap to refresh and it cannot silently drift:

    python .claude/skills/guitar-audio-intelligence/scripts/generate_codebase_map.py

Run it after adding, renaming, or removing a module, class, export or public method.
`--check` exits 1 if the committed map is stale, without writing.

Dependency-free. Regex-based, not a JS parser: it captures top-level `export`s, class
declarations, and members indented exactly one level (the convention in this codebase).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SKIP_MEMBERS = {
    "if", "for", "while", "switch", "catch", "return", "else", "do", "try",
    "setTimeout", "setInterval", "clearTimeout", "clearInterval", "requestAnimationFrame",
    "constructor",
}

EXPORT_RE = re.compile(r"^export\s+(?:default\s+)?(class|function|const|let)\s+([A-Za-z_$][\w$]*)")
CLASS_RE = re.compile(r"^(?:export\s+(?:default\s+)?)?class\s+([A-Za-z_$][\w$]*)")
# One indent level (4 spaces), optionally static/async/get/set, then name(
MEMBER_RE = re.compile(r"^ {4}(static\s+|async\s+|get\s+|set\s+)*([A-Za-z_$][\w$]*)\s*\(([^)]*)\)\s*\{")
FIELD_RE = re.compile(r"^ {4}static\s+([A-Z][A-Z0-9_]*)\s*=")


def scan(path: Path) -> dict:
    exports: list[str] = []
    classes: list[str] = []
    members: list[str] = []
    consts: list[str] = []

    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        m = EXPORT_RE.match(line)
        if m:
            exports.append(f"{m.group(1)} {m.group(2)}")
        m = CLASS_RE.match(line)
        if m and m.group(1) not in classes:
            classes.append(m.group(1))
        m = FIELD_RE.match(line)
        if m:
            consts.append(m.group(1))
            continue
        m = MEMBER_RE.match(line)
        if m:
            name = m.group(2)
            if name in SKIP_MEMBERS or name.startswith("_"):
                continue
            prefix = (m.group(1) or "").strip()
            args = " ".join(m.group(3).split())
            sig = f"{name}({args})"
            if prefix == "static":
                sig = f"static {sig}"
            if sig not in members:
                members.append(sig)

    return {"exports": exports, "classes": classes, "members": members, "consts": consts}


def render(js_root: Path, files: list[Path]) -> str:
    out: list[str] = [
        "# Codebase Map (generated)",
        "",
        "<!-- GENERATED by scripts/generate_codebase_map.py - do not edit by hand. -->",
        "",
        "Public surface of every module under `app/static/js/`. Read this instead of grepping.",
        "Private members (`_`-prefixed) and constructors are omitted; open the file for those.",
        "Regenerate after any module, class or public method changes.",
        "",
        f"{len(files)} modules.",
        "",
    ]

    for path in files:
        rel = path.relative_to(js_root).as_posix()
        info = scan(path)
        out.append(f"## `{rel}`")
        if info["exports"]:
            out.append(f"exports: {', '.join(f'`{e}`' for e in info['exports'])}")
        if info["consts"]:
            out.append(f"static constants: {', '.join(f'`{c}`' for c in info['consts'])}")
        if info["members"]:
            out.append("")
            for sig in info["members"]:
                out.append(f"- `{sig}`")
        out.append("")

    return "\n".join(out)


def main() -> int:
    here = Path(__file__).resolve()
    skill_root = here.parent.parent
    repo_root = None
    for base in here.parents:
        if (base / "app" / "static" / "js").is_dir():
            repo_root = base
            break
    if repo_root is None:
        print("FAIL  could not locate app/static/js")
        return 1

    js_root = repo_root / "app" / "static" / "js"
    files = sorted(js_root.rglob("*.js"), key=lambda p: p.relative_to(js_root).as_posix())
    content = render(js_root, files)

    target = skill_root / "references" / "codebase-map.md"
    check_only = "--check" in sys.argv

    existing = target.read_text(encoding="utf-8") if target.is_file() else None
    if existing == content:
        print(f"up to date: {target.relative_to(repo_root).as_posix()} ({len(files)} modules)")
        return 0

    if check_only:
        print(f"STALE  {target.relative_to(repo_root).as_posix()} - rerun without --check")
        return 1

    target.write_text(content, encoding="utf-8")
    verb = "wrote" if existing is None else "updated"
    approx_tokens = len(content) // 4
    print(f"{verb} {target.relative_to(repo_root).as_posix()} - {len(files)} modules, ~{approx_tokens} tokens")
    return 0


if __name__ == "__main__":
    sys.exit(main())
